FROM confluentinc/cp-kafka-connect:7.4.3

RUN confluent-hub install --no-prompt debezium/debezium-connector-postgresql:latest \
    && confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.7.4 \
    && confluent-hub install --no-prompt confluentinc/kafka-connect-s3:10.5.10

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"
